version: '3.7'

services:
  app:
    container_name: user-webserver
    build:
        context: .
        dockerfile: Dockerfile
    command: go run .
    expose:
      - "8080"
    ports:
      - "8080:8080"
